### ISSUE TITLE
NPM package does not contain type files since 1.4.1 / 2.1.0

### ISSUE THREAD

**Issue by dayflower** [Himenon/kubernetes-typescript-openapi#13]
I'm quite unsure about the correct usage of this package, however, the package built as version 1.4.1 (and 2.1.0) does not contain any valid ts file, just contains the following files only.

- LICENSE
- README.md
- package.json

Same behavior for npm/pnpm/yarn.

I'll appreciate it if you could check this issue when you have time because I love this product with empathy what you think in [your article](https://dwango.github.io/nicolive-kubernetes-migration-handbook-2022/docs/manifest/manifest-management/).

**Comment by Himenon** [comment]
Thank you. After checking, it does seem to be missing. I’ll fix it…!

![image](https://github.com/user-attachments/assets/ed5d9a11-de77-4ba9-8865-0ded31dd548c)

**Comment by Himenon** [comment]
@dayflower 

I’ve included the dist directory in version 2.1.1, so I believe it should now be usable. Please check it out…!

Thank you for the report!!!!

![image](https://github.com/user-attachments/assets/d74c3aed-0dd3-459d-9b69-ee96c80d486e)
